### ISSUE TITLE
A9 script "broken igetnonce" popup

### ISSUE THREAD

**Issue by bontek007** [rA9stuff/rA9stuff#1]
Hello.

After putting my generator 0x111111111111111 in your script it always crashes. Iphone 6s plus (15.2) in DFU; catalina Macos. Could u help me?

**Comment by bontek007** [comment]
![image](https://user-images.githubusercontent.com/54554354/152617398-b1a25ad7-08e1-4d2a-9c64-c09a6cc82907.jpeg)

**Comment by rA9stuff** [comment]
This isn’t the right place to open an issue. You have SIP enabled which prevents unsigned binaries from running. Go to the resource folder and right click every binary you see there then click open. Script should work fine after that.

**Comment by bontek007** [comment]
Sorry bro. I never used github before. Will try and let u know later. I contacted u also on Twitter about this issue. Have a nice day

**Comment by bontek007** [comment]
![image](https://user-images.githubusercontent.com/54554354/152643760-4eb5aec0-9772-4f46-a1bb-ca10e737b300.jpeg)

**Comment by bontek007** [comment]
![image](https://user-images.githubusercontent.com/54554354/152643785-ecc3d4d6-cc46-448e-9fc6-8cbb2879b9c0.jpeg)

**Comment by bontek007** [comment]
![image](https://user-images.githubusercontent.com/54554354/152643814-500d6136-df0f-4e49-9f8b-9a39e8a3642f.jpeg)

**Comment by bontek007** [comment]
![image](https://user-images.githubusercontent.com/54554354/152643830-b72bcc99-eba0-41cc-a8f3-d2cfd5396260.jpeg)

**Comment by bontek007** [comment]
Still the same issue or i do smth wrong...![image](https://user-images.githubusercontent.com/54554354/152643861-6ae2cb52-0cee-4540-b2d8-4c43d830ae3b.jpeg)

**Comment by rA9stuff** [comment]
Are you sure you opened igetnonce and irecovery as well?

**Comment by bontek007** [comment]
Yes. Please see

**Comment by bontek007** [comment]
![image](https://user-images.githubusercontent.com/54554354/152645684-567091a7-4b28-42bc-af98-6cf738fc50a0.jpeg)

**Comment by bontek007** [comment]
![image](https://user-images.githubusercontent.com/54554354/152645692-63918592-71b1-4376-a92f-8ac6ad5a935e.jpeg)

**Comment by bontek007** [comment]
![image](https://user-images.githubusercontent.com/54554354/152645703-cc440c33-5c5d-49bf-9f67-1104e5c97a3a.jpeg)

**Comment by bontek007** [comment]
![image](https://user-images.githubusercontent.com/54554354/152645718-0e434e16-b35d-4038-901b-b6ba5dddf6fb.jpeg)

**Comment by rA9stuff** [comment]
Just add me on discord, this is not an efficient way of using github issues...
`rA9#4651`
